---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uug-demo-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: uug-demo-api
  template:
    metadata:
      labels:
        app: uug-demo-api
    spec:
      containers:
        - image: 'ghcr.io/ripleymj/uug-demo-api:bf61b8d97f8c3c1c1f759b317948e68d8a513e37'
          name: uug-demo-api
          ports:
            - containerPort: 3000
