---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uug-demo-api
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uug-demo-api
                port:
                  number: 3000
